### ISSUE TITLE
Sign not found in the dictionary of signs Scorpion sing

### ISSUE THREAD

**Issue by RubenDV1995** [DerSarco/newastro#5]
al consultar https://newastro.vercel.app/Scorpion/ el API ni tiene información del singo Escorpio, en ninguna fecha ni ningún lenguaje.

{
    "error": "Sign not found in the dictionary of signs."
}

**Comment by DerSarco** [comment]
Gracias por el issue, para fixear en tu get de momento usa `scorpio` sin la N al final y obtendrás los resultados.

@erix-mx tocá arreglar el sign de Scorpio, en el list está devolviendolo con una n al final
![Screenshot 2023-08-31 at 16 51 14](https://github.com/DerSarco/newastro/assets/64336008/df8e56b6-1f56-4497-b7d3-da08edce54a7)

**Comment by RubenDV1995** [comment]
gracias eso resulte cualquier inconveniente.
